// Speaker script for the 2016 deck, one entry per slide. build2016.js writes
// each into the slide's notes; TALK2016.md is the same text for reading.
module.exports = {
  1: "Last week you asked me to open the box, define the noise, and go one SNR at a time on the four-class problem, and not to make it more complicated than that. This is that, on RML2016.10a, the dataset the group works on. Everything is measured on one model, and every number comes from a file in the repository.",
  2: "These are the six things you asked for, and the slide where each is answered. Items one to five are done. The sixth, don't make it more complicated, is how the deck is built: four classes, one model, one dataset. There is one slide near the end on the domain-gap work, because it contradicted 2018 and I want you to know that.",
  3: "The box, end to end. In: one frame, 128 complex samples, as a 2 by 128 array of I and Q. On this dataset that is 16 symbols. Each frame is scaled to unit power first, so the model cannot read the level. Two convolution layers turn it into 32 short feature vectors, each describing about one and a half symbols. A two-layer bidirectional LSTM reads those 32 forwards and backwards, so each one knows about the whole frame. Attention takes a learned weighted average of the 32, which gives one vector for the frame. A small classifier turns that into four scores, and the decision is the largest score. 785 thousand numbers are learned; 84 percent of them are in the LSTM. The same weights work at 64 and 32 samples, only the number of LSTM steps changes, and that is what makes the frame-length test clean.",
  4: "Where it came from. The architecture is ICRNNA, El-Haryqy and colleagues, Results in Engineering 2025. Our code is not written from the paper; it is transcribed from a colleague's reproduction, and it differs from the paper in five places, listed. So I never call it the published architecture. To check the paper independently I built a faithful version from the paper itself. At the paper's own 58 epochs it reaches 61.75 against 63.24. Trained until early stopping ends it, which is epoch 107, it reaches 63.21. So the paper's number is real and our pipeline reads the data correctly. And you asked who wrote what. The code, the tools, this deck and most of the write-up were written with Claude Code, Anthropic's coding assistant. Every commit it wrote is marked in git. The dataset, the architecture, the numbers and the decisions did not come from it: the numbers come from running the code on a GPU, and several were rerun and came back bit-identical. [Say here, in your own words, how the work before 9 September was done and who the colleague is.]",
  5: "How it was trained, and how it decides. The split is per class and per SNR: 70 percent train, 15 validation, 15 test. Early stopping, the learning-rate schedule and the choice of checkpoint read only validation; the test set is touched once. 14 seeds, and every one of them stopped by early stopping, not by the ceiling. On the decision: the model is deterministic. The same frame 10,000 times gives the same answer 10,000 times. So the meaningful test is 10,000 different frames, and every table in this deck counts exactly that. And there is no 'I don't know': every frame gets one of the four labels, even at minus 20 dB. That is where the sink on slide 12 comes from.",
  6: "Who made the noise. DeepSig, in GNU Radio, entirely synthetic. The paper names the channel block and gives no parameters at all, so these come from the generator code they published. The important point is on the right: noise is only one of five impairments. Carrier offset, clock offset, Rician fading and three-path multipath are there at every SNR, including plus 18. And the SNR label sets exactly one number: the noise amplitude, 10 to the minus label over 10. Two more properties. The carrier offset can go up to 500 Hz in principle, but the random walk only reaches a few hertz in a run, so within a frame it rotates by about a degree. And the generator seeds the channel with a fixed number; in today's GNU Radio that would make every run reuse the same noise, so I checked the file: among 11,000 frames at minus 20 dB, no two share a noise segment. The 2016 GNU Radio picked its noise with an unseeded generator, so the noise is fresh.",
  7: "So what is 10 dB the ratio of? Because that setting is an amplitude, the label moves the noise twice as fast as its name. I did not want to take the code's word for it, so I measured the SNR in the frames of the file itself, from the noise level outside the signal's band. For PSK the measured SNR rises 1.9 dB per dB of label. Confirmed. The second finding I did not expect: the classes do not share an SNR. At the same label, QAM16 frames have 9.5 dB more SNR than PSK and QAM64 15 dB more. That is exactly what you get if the constellations went out unscaled, with the noise the same for all. So at a label of minus 6, a QAM64 frame is at about plus 9 dB and a QPSK frame at about minus 6. The answer to your question: 10 dB in this dataset is a setting, not a ratio, and it means a different ratio for each class. The method reads between about minus 13 and plus 18 dB; outside that, the flat parts are the method's limit.",
  8: "The box at one SNR: 10 dB label. 8,400 decisions: 14 seeds, 150 test frames per class. Rows are what was sent, columns what was decided. Recall is the row: of the frames that were this class, how many were called it. Precision is the column: of the frames called this class, how many were it. BPSK and QPSK are at 99.6 percent. Almost every error is QAM16 against QAM64: 395 of the 448.",
  9: "Then lower, as you asked: 10, 6, 4, 2. The counts are 448, 473, 453, 486 wrong out of 8,400. Nothing changes. The box does not start to break until the label goes under 0 dB: 609 at 0, 1,042 at minus 2, 2,174 at minus 4. Below that, QPSK leaks into both QAMs first and QAM16 drains into QAM64; BPSK holds longest.",
  10: "Error rate against SNR, and against frame length, which you also asked for. 8,400 decisions behind every point; the band is the best and worst of 14 seeds. SNR decides where the curve falls. Frame length decides how low it can go: from plus 2 dB up, the error rate is flat at 5.7 percent with 128 samples, 15.5 with 64 and 25.2 with 32. As you predicted: shorter frames, more errors, and more SNR does not buy them back.",
  11: "What the shorter frames break. At 128 samples, 16 symbols, QAM16 recall is 87 percent. At 8 symbols, 66. At 4 symbols, 46: a coin flip. BPSK does not move. QPSK only drops at 4 symbols, and it drops into BPSK, which is what four symbols predict: if all four fall on one diagonal of the QPSK constellation, the frame looks like BPSK. With the SNR measurement from slide 7, the QAM frames here are above 17 dB. So these errors are not noise; they are the number of symbols in the frame.",
  12: "Every graph now says how many decisions are behind each point, and shows precision next to recall. This is why. At minus 20 dB, BPSK and QPSK recall are near 50 percent, which looks like recognition. It is not: 98.8 percent of all decisions go to those two, and their precision is 25 percent, which is chance with four classes. The model sends frames with no information to the PSK classes, and which of the two is arbitrary: from seed to seed the BPSK share runs from 12 to 86 percent. That is the rising curve you pointed at last week. It is the sink, and precision is what shows it.",
  13: "One slide beyond the box, because it changes what I told you about 2018. On 2018 spectral whitening closed the domain gap. On 2016 it does not. The gap is small to start with, 0.028, and the standard augmentation set closes it. Whitening at first cost 8 points in-domain. I measured why: at 128 samples the spectral envelope is estimated from too few bins. Smoothing over more bins removes the cost entirely, and at 33 bins it is even 1.3 points better than nothing, but it still does not close the cross-domain gap. So the 2018 claim holds only for 2018, and I say so.",
  14: "The caveats. Both domains are synthetic. The model is not the published architecture. The SNR label means a different SNR per class, so no comparison across classes at one label. And the four-class results are 14 seeds on one dataset and one model.",
  15: "Next, keeping to the four-class box, and breaking it one knob at a time. Frame length and SNR are done. The generator is in our hands, so the next knobs are the other four impairments: turn off carrier offset, fading and multipath one by one, at the same frame length, and see which one the high-SNR QAM errors belong to. Then the same box on a real capture, when lab access allows.",
};
